### ISSUE TITLE
Zero day Workshops

### ISSUE THREAD

**Issue by orkunkl** [InterWasm/DAO#22]
`Zero Day Workshop` is a series of workshops for taking the first step to bootstrap a newbie to pro blockchain degen dev.

This workshops target group is Software Developers without prior Blockchain experience but knows few things about bitcoin and crypto in general.

We will work on this project with @findolor @kaymakf.

## Proposed Syllabus

- What is blockchain?
- Why it matters?
- What can you do with it?
---
- What are Bitcoin and Ethereum in short, and how do they simply work.
- What is Tendermint and Cosmos SDK
- How the modules and consensus looks like
- Addresses, transactions, and signatures
---
- What is cosmwasm
- Writing, compiling, deploying contracts
- Contract Interaction
---
- CosmWasm development
  - Develop a contract based on cw20-base?
  - Use DAO contract as admin?
---
- CosmJS: **to be filled**

Let's have a general discussion about what we want to see under this issue.

**Comment by findolor** [comment]
This is a great idea since the information about cryptocurrencies, Cosmos, or any other things that are related are spread across many websites. It's easy to learn stuff but it is also really hard to become proficient along the way. 

I agree with what you wrote about the syllabus. Learning these things will greatly help people to be involved in the scene and be active in the community.

Also, I believe what we need to do is pass along the knowledge we have but also try to keep people active by giving them things to do. We could;

- Give out assignments about blockchain. To grasp the idea, they can build a simple blockchain using javascript or something similar to learn the basics while coding. It's not like writing a smart contract where you know some things about crypto, this is more like a playground. This is suitable for people who have no idea about blockchains in general and have experience coding.

- Try to give them a framework on how to associate daily/simple things with the inner workings of blockchains. Like how consensus mechanism works, how centralized systems could have flaws etc. Try to come up with easy-to-use examples. This is for people that have a hard time thinking abstract things. A video with more visual elements might help us better along the way.

- While teaching people about the benefits of blockchain technology, also teach them the pitfalls and the things that it cannot solve. It's important for people to learn both ways. They need to be aware of scams and any other bad things that could happen. I think we need to cover this area too.

- Have community challenges to make the community be more alive on its own without us constantly pushing them in a direction. This will be more engaging for them as it's easy for people to find more like-minded people by asking questions and getting answers on social channels/communities. We also might be able to find many bright minds along the way. Of course, we'll also do hackathons and other events but this is more like small competitions/activities in Discord.

- Have a dedicated channel for books and other resources that we like to share. We'll update it on weekly/monthly cycles. It's crucial that we must pass the knowledge so why not add what we read and practice.

I'll add things as I think more about it but this is what comes up to my mind for now. I think establishing a platform for learning all these things is so valuable that if we could pull this off and have a knowledge hub on this scale, this will be a huge thing for both Cosmos and the community as a whole.

**Comment by dakom** [comment]
I probably fit the target here pretty well (couple decades writing code, only a week or two in blockchain). Here's stuff I find confusing as a n00b that everyone seems to just know:

- gas: what is it, who pays it, what problems does it solve, what do devs need to consider about it?
- random lingo: why does everyone want to go to the moon? what are all the acronyms? (NFT, DOA, ...)
- is this all just a bubble, game, scam, etc. or is it legitimately an alternative to traditional finance (explain why)?
- staking
- validators
- protocols
- burning
- minting
- oracles (terra specific?)
- cw* (what is cw20 for example)
- financial terms (swap, hedge, for example)

**Comment by orkunkl** [comment]
@ethanfrey @the-frey @JakeHartnell @faddat your ideas?

**Comment by dalmoveras** [comment]
Hey guys! I'm researching about using cosmwasm in another chains. I think that is a really great topic for to tech or discuss in the ZD Workshop..

**Comment by umerj-meta** [comment]
Hi everyone, we are planning to build a social platform related to nfts so we are doing some research to choose between cosmwasm(cosmos) or ethereum,our concern is that as ethereum have a large user base we might lose them if we choose cosmwasm, as cosmwasm provides migration and multichain support my question is can we move the code to ethereum ecosystem using metamask  so that we can target ethereum's userbase too, what's your suggestions on that? Is it even possible to do that somehow? Are we thinking in right direction? This can be a great topic to discuss interoperability of both.
